map_type: costmap
transform_tolerance: 0.5
obstacle_range: 2.5
max_obstacle_height: 2.0
raytrace_range: 3.0
inflation_radius: 0.6
cost_scaling_factor: 15.0
lethal_cost_threshold: 100

observation_sources: scan

scan: {sensor_frame: openni_camera, data_type: LaserScan, expected_update_rate: 0.2,
  observation_persistance: 0.0, marking: true, clearing: true}
